theme: jekyll-theme-midnight
author: Steven Schifter
title: Steven Schifter’s Clarion Projects
description: Clarion projects that I created in my spare time
show_downloads: true
github:
    zip_url: https://github.com/StevenSchifter/ClarionProjects/zipball/main
    tar_url: https://github.com/StevenSchifter/ClarionProjects/tarball/main