    MEMBER('CoolBox.clw')
    
    MAP
        INCLUDE('CoolBoxHand.inc'),ONCE
    END

!!! <summary>
!!! Typed by hand to see if it could be generated by a template
!!! </summary>
HandTypedProc    PROCEDURE
    CODE
    MESSAGE('I typed this message by hand!')